// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Qe7vbzE04n6HyTufzizU3u8DJprycQ4',
    appId: '1:684033575293:web:c7c38a2ef0239436dce414',
    messagingSenderId: '684033575293',
    projectId: 'fir-crud-234a9',
    authDomain: 'fir-crud-234a9.firebaseapp.com',
    storageBucket: 'fir-crud-234a9.firebasestorage.app',
    measurementId: 'G-BS6ZPXL97E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAy0sAtIwd8Kv9oTvjTF-fHYpzkhDy3k0',
    appId: '1:684033575293:android:caf9d592f13af962dce414',
    messagingSenderId: '684033575293',
    projectId: 'fir-crud-234a9',
    storageBucket: 'fir-crud-234a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoCNFtQzj-UoKaVMJ4b99K8W12ejse_s',
    appId: '1:684033575293:ios:8f97151d4af110e2dce414',
    messagingSenderId: '684033575293',
    projectId: 'fir-crud-234a9',
    storageBucket: 'fir-crud-234a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdoCNFtQzj-UoKaVMJ4b99K8W12ejse_s',
    appId: '1:684033575293:ios:8f97151d4af110e2dce414',
    messagingSenderId: '684033575293',
    projectId: 'fir-crud-234a9',
    storageBucket: 'fir-crud-234a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Qe7vbzE04n6HyTufzizU3u8DJprycQ4',
    appId: '1:684033575293:web:577b53f581d1e9c2dce414',
    messagingSenderId: '684033575293',
    projectId: 'fir-crud-234a9',
    authDomain: 'fir-crud-234a9.firebaseapp.com',
    storageBucket: 'fir-crud-234a9.firebasestorage.app',
    measurementId: 'G-DGRVP74YQG',
  );

}